### ISSUE TITLE
Reloading repeatedly erased my notes

### ISSUE THREAD

**Issue by The-Eighth-Man** [avr/obsidian-reading-time#2]
When in preview mode and reloading (cmd + R), the text doesn't appear. I have to go into edit mode to see the text, but later on when I reloaded it deleted my note content, now I lost all inside.

**Comment by avr** [comment]
Thanks for the report - I'll take a look.

**Comment by lishid** [comment]
Another report popped up - seems like the "change" event in CodeMirror threw and error and crashed the entire editor, causing the data loss.

![image](https://user-images.githubusercontent.com/609710/98197580-100c6280-1ef5-11eb-8ef9-a89d61407aa4.png)

**Comment by lishid** [comment]
Missing a null pointer check here for `activeLeaf`: https://github.com/avr/obsidian-reading-time/blob/0717c457f7b9ad55f63ad6c6326b0d2e9f9e4d75/main.ts#L27

Also would be useful just to wrap the whole function up in try...catch just in case it kills the editor again.

**Comment by avr** [comment]
@lishid - Thanks for the pointers here.
