### ISSUE TITLE
When selecting text show reading time for the selection

### ISSUE THREAD

**Issue by dantz** [avr/obsidian-reading-time#4]
Would be great to check segments of the overall text for length.

**Comment by avr** [comment]
@dantz - This has been added to the next update.

**Comment by avr** [comment]
This has been released in 1.1.0

**Comment by AMGMNPLK** [comment]
How can I deactivate that command from command panel? It doesn't work and I don't need that function that hinder me when I'm looking for the time function of Template. Thank you for the rest of functions.
