### ISSUE TITLE
0 minutes if under 30s

### ISSUE THREAD

**Issue by redactedscribe** [avr/obsidian-reading-time#9]
If a document takes less than 30 seconds to read, display `0 min read`, `<1 min read`, or `30 sec read`. This would indicate that there likely isn't even a full paragraph's worth of text in the document.

**Comment by redactedscribe** [comment]
In fact, it would probably be nice if an accurate value could be shown down to the second if below a minute, and then hour and minute values when above 60 minutes.

**Comment by avr** [comment]
I think you can accomplish this (or something similar) by changing the output format in the plugin settings.

If you use "simple" - you should get seconds level accuracy. Let me know if that works.

**Comment by redactedscribe** [comment]
You are correct. I've been reviewing too many similar plugins and I apparently missed this option. Sorry!
